apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc-jegan  #Replace 'jegan' with your name
      containers:
      - name: mysql
        image: bitnami/mariadb:latest
        imagePullPolicy: IfNotPresent

        volumeMounts:
        - name: mysql-storage
          mountPath: /bitnami/mariadb/data

        env:
        - name: MARIADB_ROOT_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: mysql-login-credentials
              key: password

        - name: MARIADB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-configs
              key: db_name
