apiVersion: v1
kind: Pod
metadata:
  labels:
    run: hello
  name: hello
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: disk
            operator: In
            values:
            - ssd
  containers:
  - image: bitnami/nginx:latest
    name: nginx
    imagePullPolicy: IfNotPresent
